name: Download binaries

runs:
  using: composite
  steps:

  - uses: ./.github/actions/download-lego

  - name: Download recompiled binaries
    shell: bash
    run: |
      wget https://github.com/isledecomp/isle/releases/download/continuous/ReproBit-Debug-Companion.zip
      unzip -q ReproBit-Debug-Companion.zip -d companion
      mv companion/LEGO1.PDB companion/LEGO1.pdb

  - name: Upload binaries
    uses: actions/upload-artifact@v7
    with:
      name: binaries
      path: |
        binfiles
        companion
