name: Setup isle
description: Install reccmp and wine, restore the sample binaries, and detect the isle project

inputs:
  project:
    description: Detect the binaries of the isle project
    default: 'true'

runs:
  using: composite
  steps:

  - uses: actions/setup-python@v7
    with:
      python-version: '3.14'

  - name: Install reccmp
    shell: bash
    run: |
      pip install .

  - name: Install wine
    shell: bash
    run: |
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends wine wine32:i386

  - name: Restore binaries
    uses: actions/download-artifact@v7
    with:
      name: binaries

  - name: Detect binaries
    if: ${{ inputs.project == 'true' }}
    shell: bash
    working-directory: ./companion/source
    run: |
      reccmp-project detect --search-path ../../binfiles
      reccmp-project detect --what recompiled --search-path ..
