name: Prepare sample binaries

on:
  workflow_call:

jobs:
  lego:
    name: Download LEGO
    uses: ./.github/workflows/binfile-lego.yml

  ski:
    name: Download SKI
    uses: ./.github/workflows/binfile-ski.yml

  merge:
    needs: [lego, ski]
    runs-on: ubuntu-latest
    steps:

    - name: Restore LEGO
      uses: actions/cache/restore@v3
      with:
        path: 'LEGO1.DLL'
        key: legobin2
        fail-on-cache-miss: true

    - name: Restore SKI
      uses: actions/cache/restore@v3
      with:
        path: 'SKI.EXE'
        key: skibin2
        fail-on-cache-miss: true

    - name: Archive binfiles
      shell: bash
      run: |
        zip binfiles.zip *.dll *.exe

    - name: Cache binfiles
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: binfiles.zip
        key: binfiles-${{ hashFiles('binfiles.zip') }}
        restore-keys: binfiles
