name: Integration

on: [push, pull_request]

env:
  WINEDEBUG: -all

jobs:
  download:
    name: Download binaries
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/download-binaries

  reccmp:
    name: Compare ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: download
    strategy:
      fail-fast: false
      matrix:
        target: [ISLE, LEGO1, CONFIG]
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/setup-isle

    - name: Run reccmp
      shell: bash
      working-directory: ./companion/source
      run: |
        reccmp-reccmp --target ${{ matrix.target }} | tee result.txt
        grep -qE '^Implemented: +[0-9.]+% +\([1-9][0-9]*' result.txt
        grep -qE '^Accuracy: +[0-9.]+%' result.txt
        grep -E '^(Implemented|Accuracy|Progress):' result.txt >> "$GITHUB_STEP_SUMMARY"

    - name: Download saved report
      shell: bash
      run: |
        wget https://github.com/isledecomp/isle/releases/download/continuous/${{ matrix.target }}PROGRESS-dev.json

    - name: Diff against saved report
      shell: bash
      working-directory: ./companion/source
      run: |
        reccmp-reccmp --target ${{ matrix.target }} --diff ../../${{ matrix.target }}PROGRESS-dev.json 2>&1 | tee diff.txt
        ! grep -q 'Traceback (most recent call last)' diff.txt
        ! grep -q 'Could not open JSON report file' diff.txt

  tools:
    name: ${{ matrix.tool }}
    runs-on: ubuntu-latest
    needs: download
    strategy:
      fail-fast: false
      matrix:
        tool: [verexp, vtable, datacmp, decomplint, roadmap]
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/setup-isle

    - name: Run ${{ matrix.tool }}
      shell: bash
      working-directory: ./companion/source
      run: |
        reccmp-${{ matrix.tool }} --target LEGO1 2>&1 | tee output.txt || true
        ! grep -q 'Traceback (most recent call last)' output.txt

  stackcmp:
    name: stackcmp
    runs-on: ubuntu-latest
    needs: download
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/setup-isle

    - name: Run stackcmp
      shell: bash
      working-directory: ./companion/source
      run: |
        reccmp-stackcmp --target LEGO1 0x100ae350 2>&1 | tee output.txt || true
        ! grep -q 'Traceback (most recent call last)' output.txt
        ! grep -q 'Failed to find a match' output.txt

  cvdump:
    name: cvdump
    runs-on: ubuntu-latest
    needs: download
    steps:

    - uses: actions/checkout@v7

    - uses: ./.github/actions/setup-isle
      with:
        project: 'false'

    - name: Read PUBLICS section
      shell: bash
      run: |
        reccmp-cvdump -p companion/LEGO1.pdb -o publics.txt
        grep -q '^\*\*\* PUBLICS' publics.txt
        test "$(grep -c '^S_PUB32: \[' publics.txt)" -gt 0
